name: test-single-ioc
include:
  - cf-compose.yml
services:
  recc1:
    extends:
      file: ../compose.yml
      service: recc
    depends_on:
      cf:
        condition: service_healthy
        restart: true
    hostname: recc1
    networks:
      - net-1-recc-1
      - net-2-cf
  ioc1-1:
    extends:
      file: ../../client/ioc-compose.yml
      service: ioc1
    depends_on:
      recc1:
        condition: service_healthy
        restart: true
    environment:
      - IOCSH_NAME=IOC1-1
    hostname: ioc1-1
    networks:
      - net-1-recc-1

networks:
  net-1-recc-1:
    driver: bridge
